FROM golang:1.25.0-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o seeder ./cmd/seed


FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/seeder .

ENTRYPOINT ["./seeder"]