version: '3.8'

services:
  # Сервис для MongoDB
  mongodb:
    image: mongo:6.0
    container_name: sviper-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - sviper-network

  backend:
    build:
      context: ./gin-api
      dockerfile: Dockerfile
    container_name: sviper-backend
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: "mongodb://root:example@mongodb:27017"
    depends_on:
      - mongodb
    networks:
      - sviper-network

# Настройка volumes для MongoDB
volumes:
  mongodb_data:

# Настройка сети
networks:
  sviper-network:
    driver: bridge