// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuthResponseTokenType.
const (
	Bearer AuthResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the AuthResponseTokenType enum.
func (e AuthResponseTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseErrorCode.
const (
	INTERNALERROR               ErrorResponseErrorCode = "INTERNAL_ERROR"
	INVALIDCREDENTIALS          ErrorResponseErrorCode = "INVALID_CREDENTIALS"
	INVALIDPLAYLIST             ErrorResponseErrorCode = "INVALID_PLAYLIST"
	INVALIDPLAYLISTID           ErrorResponseErrorCode = "INVALID_PLAYLIST_ID"
	INVALIDPLAYLISTNAME         ErrorResponseErrorCode = "INVALID_PLAYLIST_NAME"
	INVALIDREQUEST              ErrorResponseErrorCode = "INVALID_REQUEST"
	INVALIDTRACK                ErrorResponseErrorCode = "INVALID_TRACK"
	INVALIDTRACKARTIST          ErrorResponseErrorCode = "INVALID_TRACK_ARTIST"
	INVALIDTRACKID              ErrorResponseErrorCode = "INVALID_TRACK_ID"
	INVALIDTRACKTITLE           ErrorResponseErrorCode = "INVALID_TRACK_TITLE"
	INVALIDTRACKURL             ErrorResponseErrorCode = "INVALID_TRACK_URL"
	INVALIDTRACKYEAR            ErrorResponseErrorCode = "INVALID_TRACK_YEAR"
	PLAYLISTALREADYEXISTS       ErrorResponseErrorCode = "PLAYLIST_ALREADY_EXISTS"
	PLAYLISTNOTFOUND            ErrorResponseErrorCode = "PLAYLIST_NOT_FOUND"
	TRACKALREADYEXISTS          ErrorResponseErrorCode = "TRACK_ALREADY_EXISTS"
	TRACKNOTFOUND               ErrorResponseErrorCode = "TRACK_NOT_FOUND"
	UNAUTHORIZED                ErrorResponseErrorCode = "UNAUTHORIZED"
	USERALREADYEXISTS           ErrorResponseErrorCode = "USER_ALREADY_EXISTS"
	VERIFICATIONEXPIRED         ErrorResponseErrorCode = "VERIFICATION_EXPIRED"
	VERIFICATIONINVALID         ErrorResponseErrorCode = "VERIFICATION_INVALID"
	VERIFICATIONRATELIMITED     ErrorResponseErrorCode = "VERIFICATION_RATE_LIMITED"
	VERIFICATIONTOOMANYATTEMPTS ErrorResponseErrorCode = "VERIFICATION_TOO_MANY_ATTEMPTS"
)

// Valid indicates whether the value is a known member of the ErrorResponseErrorCode enum.
func (e ErrorResponseErrorCode) Valid() bool {
	switch e {
	case INTERNALERROR:
		return true
	case INVALIDCREDENTIALS:
		return true
	case INVALIDPLAYLIST:
		return true
	case INVALIDPLAYLISTID:
		return true
	case INVALIDPLAYLISTNAME:
		return true
	case INVALIDREQUEST:
		return true
	case INVALIDTRACK:
		return true
	case INVALIDTRACKARTIST:
		return true
	case INVALIDTRACKID:
		return true
	case INVALIDTRACKTITLE:
		return true
	case INVALIDTRACKURL:
		return true
	case INVALIDTRACKYEAR:
		return true
	case PLAYLISTALREADYEXISTS:
		return true
	case PLAYLISTNOTFOUND:
		return true
	case TRACKALREADYEXISTS:
		return true
	case TRACKNOTFOUND:
		return true
	case UNAUTHORIZED:
		return true
	case USERALREADYEXISTS:
		return true
	case VERIFICATIONEXPIRED:
		return true
	case VERIFICATIONINVALID:
		return true
	case VERIFICATIONRATELIMITED:
		return true
	case VERIFICATIONTOOMANYATTEMPTS:
		return true
	default:
		return false
	}
}

// Defines values for PlaylistVisibility.
const (
	Private PlaylistVisibility = "private"
	Public  PlaylistVisibility = "public"
)

// Valid indicates whether the value is a known member of the PlaylistVisibility enum.
func (e PlaylistVisibility) Valid() bool {
	switch e {
	case Private:
		return true
	case Public:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken  string                `json:"access_token"`
	ExpiresIn    int32                 `json:"expires_in"`
	RefreshToken string                `json:"refresh_token"`
	TokenType    AuthResponseTokenType `json:"token_type"`
}

// AuthResponseTokenType defines model for AuthResponse.TokenType.
type AuthResponseTokenType string

// CreatePlaylistRequest defines model for CreatePlaylistRequest.
type CreatePlaylistRequest struct {
	// Name Example: My Workout
	Name       string              `json:"name"`
	Visibility *PlaylistVisibility `json:"visibility,omitempty"`
}

// CreateTrackRequest defines model for CreateTrackRequest.
type CreateTrackRequest struct {
	AlbumArtURL string   `json:"albumArtURL"`
	AlbumTitle  string   `json:"albumTitle"`
	Artist      string   `json:"artist"`
	Genre       []string `json:"genre"`

	// Id Example: track-001
	Id         string `json:"id"`
	PreviewURL string `json:"previewURL"`
	Title      string `json:"title"`
	Url        string `json:"url"`
	Year       int    `json:"year"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		// Code Example: PLAYLIST_NOT_FOUND
		Code ErrorResponseErrorCode `json:"code"`

		// Message Example: playlist not found
		Message string `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode Example: PLAYLIST_NOT_FOUND
type ErrorResponseErrorCode string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Data struct {
		// Message Example: track added to playlist
		Message string `json:"message"`
	} `json:"data"`
}

// Playlist defines model for Playlist.
type Playlist struct {
	// Id Playlist identifier
	//
	// Example: 66c8b7e2b0e9c6a8c9a2d123
	Id string `json:"id"`

	// Name Playlist name
	//
	// Example: My Workout
	Name string `json:"name"`

	// Tracks Track identifiers contained in the playlist
	//
	// Example: ["track-001","track-002"]
	Tracks     []string            `json:"tracks"`
	Visibility *PlaylistVisibility `json:"visibility,omitempty"`
}

// PlaylistResponse defines model for PlaylistResponse.
type PlaylistResponse struct {
	Data Playlist `json:"data"`
}

// PlaylistVisibility defines model for PlaylistVisibility.
type PlaylistVisibility string

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse struct {
	ExpiresIn      int32              `json:"expires_in"`
	VerificationId openapi_types.UUID `json:"verification_id"`
}

// RegistrationVerificationResponse defines model for RegistrationVerificationResponse.
type RegistrationVerificationResponse struct {
	ExpiresIn      int32              `json:"expires_in"`
	RetryAfter     int32              `json:"retry_after"`
	VerificationId openapi_types.UUID `json:"verification_id"`
}

// ResendRegistrationVerificationRequest defines model for ResendRegistrationVerificationRequest.
type ResendRegistrationVerificationRequest struct {
	VerificationId openapi_types.UUID `json:"verification_id"`
}

// Track defines model for Track.
type Track struct {
	// AlbumArtURL Example: https://example.com/album.jpg
	AlbumArtURL string `json:"albumArtURL"`

	// AlbumTitle Example: Album
	AlbumTitle string `json:"albumTitle"`

	// Artist Example: Artist
	Artist string `json:"artist"`

	// Genre Example: ["Rock","Alternative"]
	Genre []string `json:"genre"`

	// Id Example: track-001
	Id string `json:"id"`

	// PreviewURL Example: https://example.com/preview.mp3
	PreviewURL string `json:"previewURL"`

	// Title Example: Song Title
	Title string `json:"title"`

	// Url Example: https://example.com/song.mp3
	Url string `json:"url"`

	// Year Example: 2025
	Year int `json:"year"`
}

// TrackListResponse defines model for TrackListResponse.
type TrackListResponse struct {
	Data []Track `json:"data"`
}

// TrackResponse defines model for TrackResponse.
type TrackResponse struct {
	Data Track `json:"data"`
}

// UpdatePlaylistRequest defines model for UpdatePlaylistRequest.
type UpdatePlaylistRequest struct {
	// Name Example: Updated Workout
	Name       string              `json:"name"`
	Visibility *PlaylistVisibility `json:"visibility,omitempty"`
}

// UpdateTrackRequest defines model for UpdateTrackRequest.
type UpdateTrackRequest struct {
	AlbumArtURL string   `json:"albumArtURL"`
	AlbumTitle  string   `json:"albumTitle"`
	Artist      string   `json:"artist"`
	Genre       []string `json:"genre"`
	PreviewURL  string   `json:"previewURL"`
	Title       string   `json:"title"`
	Url         string   `json:"url"`
	Year        int      `json:"year"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Email openapi_types.Email `json:"email"`
	Id    openapi_types.UUID  `json:"id"`
}

// VerifyRegistrationRequest defines model for VerifyRegistrationRequest.
type VerifyRegistrationRequest struct {
	Code           string             `json:"code"`
	VerificationId openapi_types.UUID `json:"verification_id"`
}

// PlaylistId defines model for PlaylistId.
type PlaylistId = string

// TrackId defines model for TrackId.
type TrackId = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = LogoutRequest

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// ResendRegistrationVerificationJSONRequestBody defines body for ResendRegistrationVerification for application/json ContentType.
type ResendRegistrationVerificationJSONRequestBody = ResendRegistrationVerificationRequest

// VerifyRegistrationJSONRequestBody defines body for VerifyRegistration for application/json ContentType.
type VerifyRegistrationJSONRequestBody = VerifyRegistrationRequest

// CreatePlaylistJSONRequestBody defines body for CreatePlaylist for application/json ContentType.
type CreatePlaylistJSONRequestBody = CreatePlaylistRequest

// UpdatePlaylistJSONRequestBody defines body for UpdatePlaylist for application/json ContentType.
type UpdatePlaylistJSONRequestBody = UpdatePlaylistRequest

// CreateTrackJSONRequestBody defines body for CreateTrack for application/json ContentType.
type CreateTrackJSONRequestBody = CreateTrackRequest

// UpdateTrackJSONRequestBody defines body for UpdateTrack for application/json ContentType.
type UpdateTrackJSONRequestBody = UpdateTrackRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login Login user
	// (POST /auth/login)
	Login(c *gin.Context)
	// Logout Logout user
	// (POST /auth/logout)
	Logout(c *gin.Context)
	// Refresh Refresh access token
	// (POST /auth/refresh)
	Refresh(c *gin.Context)
	// Register Start user registration
	// (POST /auth/register)
	Register(c *gin.Context)
	// ResendRegistrationVerification Resend registration verification code
	// (POST /auth/register/resend)
	ResendRegistrationVerification(c *gin.Context)
	// VerifyRegistration Verify user email during registration
	// (POST /auth/register/verify)
	VerifyRegistration(c *gin.Context)
	// CreatePlaylist Create playlist
	// (POST /playlists)
	CreatePlaylist(c *gin.Context)
	// DeletePlaylist Delete playlist
	// (DELETE /playlists/{playlistId})
	DeletePlaylist(c *gin.Context, playlistId PlaylistId)
	// GetPlaylistByID Get playlist by ID
	// (GET /playlists/{playlistId})
	GetPlaylistByID(c *gin.Context, playlistId PlaylistId)
	// UpdatePlaylist Update playlist
	// (PUT /playlists/{playlistId})
	UpdatePlaylist(c *gin.Context, playlistId PlaylistId)
	// RemoveTrackFromPlaylist Remove track from playlist
	// (DELETE /playlists/{playlistId}/tracks/{trackId})
	RemoveTrackFromPlaylist(c *gin.Context, playlistId PlaylistId, trackId TrackId)
	// AddTrackToPlaylist Add track to playlist
	// (POST /playlists/{playlistId}/tracks/{trackId})
	AddTrackToPlaylist(c *gin.Context, playlistId PlaylistId, trackId TrackId)
	// GetAllTracks Get all tracks
	// (GET /tracks)
	GetAllTracks(c *gin.Context)
	// CreateTrack Create track
	// (POST /tracks)
	CreateTrack(c *gin.Context)
	// DeleteTrack Delete track
	// (DELETE /tracks/{trackId})
	DeleteTrack(c *gin.Context, trackId TrackId)
	// GetTrackByID Get track by ID
	// (GET /tracks/{trackId})
	GetTrackByID(c *gin.Context, trackId TrackId)
	// UpdateTrack Update track
	// (PUT /tracks/{trackId})
	UpdateTrack(c *gin.Context, trackId TrackId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// Refresh operation middleware
func (siw *ServerInterfaceWrapper) Refresh(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Refresh(c)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Register(c)
}

// ResendRegistrationVerification operation middleware
func (siw *ServerInterfaceWrapper) ResendRegistrationVerification(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResendRegistrationVerification(c)
}

// VerifyRegistration operation middleware
func (siw *ServerInterfaceWrapper) VerifyRegistration(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.VerifyRegistration(c)
}

// CreatePlaylist operation middleware
func (siw *ServerInterfaceWrapper) CreatePlaylist(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreatePlaylist(c)
}

// DeletePlaylist operation middleware
func (siw *ServerInterfaceWrapper) DeletePlaylist(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "playlistId" -------------
	var playlistId PlaylistId

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", c.Param("playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter playlistId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeletePlaylist(c, playlistId)
}

// GetPlaylistByID operation middleware
func (siw *ServerInterfaceWrapper) GetPlaylistByID(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "playlistId" -------------
	var playlistId PlaylistId

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", c.Param("playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter playlistId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPlaylistByID(c, playlistId)
}

// UpdatePlaylist operation middleware
func (siw *ServerInterfaceWrapper) UpdatePlaylist(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "playlistId" -------------
	var playlistId PlaylistId

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", c.Param("playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter playlistId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdatePlaylist(c, playlistId)
}

// RemoveTrackFromPlaylist operation middleware
func (siw *ServerInterfaceWrapper) RemoveTrackFromPlaylist(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "playlistId" -------------
	var playlistId PlaylistId

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", c.Param("playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter playlistId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "trackId" -------------
	var trackId TrackId

	err = runtime.BindStyledParameterWithOptions("simple", "trackId", c.Param("trackId"), &trackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter trackId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveTrackFromPlaylist(c, playlistId, trackId)
}

// AddTrackToPlaylist operation middleware
func (siw *ServerInterfaceWrapper) AddTrackToPlaylist(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "playlistId" -------------
	var playlistId PlaylistId

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", c.Param("playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter playlistId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "trackId" -------------
	var trackId TrackId

	err = runtime.BindStyledParameterWithOptions("simple", "trackId", c.Param("trackId"), &trackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter trackId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddTrackToPlaylist(c, playlistId, trackId)
}

// GetAllTracks operation middleware
func (siw *ServerInterfaceWrapper) GetAllTracks(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAllTracks(c)
}

// CreateTrack operation middleware
func (siw *ServerInterfaceWrapper) CreateTrack(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTrack(c)
}

// DeleteTrack operation middleware
func (siw *ServerInterfaceWrapper) DeleteTrack(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "trackId" -------------
	var trackId TrackId

	err = runtime.BindStyledParameterWithOptions("simple", "trackId", c.Param("trackId"), &trackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter trackId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteTrack(c, trackId)
}

// GetTrackByID operation middleware
func (siw *ServerInterfaceWrapper) GetTrackByID(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "trackId" -------------
	var trackId TrackId

	err = runtime.BindStyledParameterWithOptions("simple", "trackId", c.Param("trackId"), &trackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter trackId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTrackByID(c, trackId)
}

// UpdateTrack operation middleware
func (siw *ServerInterfaceWrapper) UpdateTrack(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "trackId" -------------
	var trackId TrackId

	err = runtime.BindStyledParameterWithOptions("simple", "trackId", c.Param("trackId"), &trackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter trackId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateTrack(c, trackId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/register", wrapper.Register)
	router.POST(options.BaseURL+"/auth/register/verify", wrapper.VerifyRegistration)
	router.POST(options.BaseURL+"/auth/register/resend", wrapper.ResendRegistrationVerification)
	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/refresh", wrapper.Refresh)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout)
	router.GET(options.BaseURL+"/tracks", wrapper.GetAllTracks)
	router.POST(options.BaseURL+"/tracks", wrapper.CreateTrack)
	router.DELETE(options.BaseURL+"/tracks/:trackId", wrapper.DeleteTrack)
	router.GET(options.BaseURL+"/tracks/:trackId", wrapper.GetTrackByID)
	router.PUT(options.BaseURL+"/tracks/:trackId", wrapper.UpdateTrack)
	router.POST(options.BaseURL+"/playlists", wrapper.CreatePlaylist)
	router.DELETE(options.BaseURL+"/playlists/:playlistId", wrapper.DeletePlaylist)
	router.GET(options.BaseURL+"/playlists/:playlistId", wrapper.GetPlaylistByID)
	router.PUT(options.BaseURL+"/playlists/:playlistId", wrapper.UpdatePlaylist)
	router.DELETE(options.BaseURL+"/playlists/:playlistId/tracks/:trackId", wrapper.RemoveTrackFromPlaylist)
	router.POST(options.BaseURL+"/playlists/:playlistId/tracks/:trackId", wrapper.AddTrackToPlaylist)
}

type BadRequestJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type TooManyRequestsResponseHeaders struct {
	RetryAfter *int32
}
type TooManyRequestsJSONResponse struct {
	Body ErrorResponse

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedJSONResponse ErrorResponse

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login400JSONResponse struct{ BadRequestJSONResponse }

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response Login500JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
	Body *LogoutJSONRequestBody
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Logout400JSONResponse struct{ BadRequestJSONResponse }

func (response Logout400JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Logout500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response Logout500JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshRequestObject struct {
	Body *RefreshJSONRequestBody
}

type RefreshResponseObject interface {
	VisitRefreshResponse(w http.ResponseWriter) error
}

type Refresh200JSONResponse AuthResponse

func (response Refresh200JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Refresh400JSONResponse struct{ BadRequestJSONResponse }

func (response Refresh400JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Refresh401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Refresh401JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Refresh500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response Refresh500JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register202JSONResponse RegisterResponse

func (response Register202JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type Register400JSONResponse struct{ BadRequestJSONResponse }

func (response Register400JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Register409JSONResponse struct{ ConflictJSONResponse }

func (response Register409JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type Register429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response Register429JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type Register500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response Register500JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ResendRegistrationVerificationRequestObject struct {
	Body *ResendRegistrationVerificationJSONRequestBody
}

type ResendRegistrationVerificationResponseObject interface {
	VisitResendRegistrationVerificationResponse(w http.ResponseWriter) error
}

type ResendRegistrationVerification202JSONResponse RegistrationVerificationResponse

func (response ResendRegistrationVerification202JSONResponse) VisitResendRegistrationVerificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type ResendRegistrationVerification400JSONResponse struct{ BadRequestJSONResponse }

func (response ResendRegistrationVerification400JSONResponse) VisitResendRegistrationVerificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ResendRegistrationVerification404JSONResponse struct{ NotFoundJSONResponse }

func (response ResendRegistrationVerification404JSONResponse) VisitResendRegistrationVerificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ResendRegistrationVerification429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response ResendRegistrationVerification429JSONResponse) VisitResendRegistrationVerificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ResendRegistrationVerification500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ResendRegistrationVerification500JSONResponse) VisitResendRegistrationVerificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyRegistrationRequestObject struct {
	Body *VerifyRegistrationJSONRequestBody
}

type VerifyRegistrationResponseObject interface {
	VisitVerifyRegistrationResponse(w http.ResponseWriter) error
}

type VerifyRegistration201JSONResponse UserResponse

func (response VerifyRegistration201JSONResponse) VisitVerifyRegistrationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyRegistration400JSONResponse struct{ BadRequestJSONResponse }

func (response VerifyRegistration400JSONResponse) VisitVerifyRegistrationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyRegistration404JSONResponse struct{ NotFoundJSONResponse }

func (response VerifyRegistration404JSONResponse) VisitVerifyRegistrationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyRegistration409JSONResponse struct{ ConflictJSONResponse }

func (response VerifyRegistration409JSONResponse) VisitVerifyRegistrationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyRegistration429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response VerifyRegistration429JSONResponse) VisitVerifyRegistrationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyRegistration500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response VerifyRegistration500JSONResponse) VisitVerifyRegistrationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlaylistRequestObject struct {
	Body *CreatePlaylistJSONRequestBody
}

type CreatePlaylistResponseObject interface {
	VisitCreatePlaylistResponse(w http.ResponseWriter) error
}

type CreatePlaylist201JSONResponse PlaylistResponse

func (response CreatePlaylist201JSONResponse) VisitCreatePlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlaylist400JSONResponse struct{ BadRequestJSONResponse }

func (response CreatePlaylist400JSONResponse) VisitCreatePlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlaylist401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreatePlaylist401JSONResponse) VisitCreatePlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlaylist409JSONResponse struct{ ConflictJSONResponse }

func (response CreatePlaylist409JSONResponse) VisitCreatePlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlaylist500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreatePlaylist500JSONResponse) VisitCreatePlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeletePlaylistRequestObject struct {
	PlaylistId PlaylistId `json:"playlistId"`
}

type DeletePlaylistResponseObject interface {
	VisitDeletePlaylistResponse(w http.ResponseWriter) error
}

type DeletePlaylist204Response struct {
}

func (response DeletePlaylist204Response) VisitDeletePlaylistResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeletePlaylist400JSONResponse struct{ BadRequestJSONResponse }

func (response DeletePlaylist400JSONResponse) VisitDeletePlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeletePlaylist401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeletePlaylist401JSONResponse) VisitDeletePlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeletePlaylist404JSONResponse struct{ NotFoundJSONResponse }

func (response DeletePlaylist404JSONResponse) VisitDeletePlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeletePlaylist500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeletePlaylist500JSONResponse) VisitDeletePlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlaylistByIDRequestObject struct {
	PlaylistId PlaylistId `json:"playlistId"`
}

type GetPlaylistByIDResponseObject interface {
	VisitGetPlaylistByIDResponse(w http.ResponseWriter) error
}

type GetPlaylistByID200JSONResponse PlaylistResponse

func (response GetPlaylistByID200JSONResponse) VisitGetPlaylistByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlaylistByID400JSONResponse struct{ BadRequestJSONResponse }

func (response GetPlaylistByID400JSONResponse) VisitGetPlaylistByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlaylistByID404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPlaylistByID404JSONResponse) VisitGetPlaylistByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlaylistByID500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetPlaylistByID500JSONResponse) VisitGetPlaylistByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePlaylistRequestObject struct {
	PlaylistId PlaylistId `json:"playlistId"`
	Body       *UpdatePlaylistJSONRequestBody
}

type UpdatePlaylistResponseObject interface {
	VisitUpdatePlaylistResponse(w http.ResponseWriter) error
}

type UpdatePlaylist200JSONResponse PlaylistResponse

func (response UpdatePlaylist200JSONResponse) VisitUpdatePlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePlaylist400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdatePlaylist400JSONResponse) VisitUpdatePlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePlaylist401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdatePlaylist401JSONResponse) VisitUpdatePlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePlaylist404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdatePlaylist404JSONResponse) VisitUpdatePlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePlaylist500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdatePlaylist500JSONResponse) VisitUpdatePlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RemoveTrackFromPlaylistRequestObject struct {
	PlaylistId PlaylistId `json:"playlistId"`
	TrackId    TrackId    `json:"trackId"`
}

type RemoveTrackFromPlaylistResponseObject interface {
	VisitRemoveTrackFromPlaylistResponse(w http.ResponseWriter) error
}

type RemoveTrackFromPlaylist204Response struct {
}

func (response RemoveTrackFromPlaylist204Response) VisitRemoveTrackFromPlaylistResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RemoveTrackFromPlaylist400JSONResponse struct{ BadRequestJSONResponse }

func (response RemoveTrackFromPlaylist400JSONResponse) VisitRemoveTrackFromPlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RemoveTrackFromPlaylist401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RemoveTrackFromPlaylist401JSONResponse) VisitRemoveTrackFromPlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RemoveTrackFromPlaylist404JSONResponse struct{ NotFoundJSONResponse }

func (response RemoveTrackFromPlaylist404JSONResponse) VisitRemoveTrackFromPlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RemoveTrackFromPlaylist500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response RemoveTrackFromPlaylist500JSONResponse) VisitRemoveTrackFromPlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type AddTrackToPlaylistRequestObject struct {
	PlaylistId PlaylistId `json:"playlistId"`
	TrackId    TrackId    `json:"trackId"`
}

type AddTrackToPlaylistResponseObject interface {
	VisitAddTrackToPlaylistResponse(w http.ResponseWriter) error
}

type AddTrackToPlaylist200JSONResponse MessageResponse

func (response AddTrackToPlaylist200JSONResponse) VisitAddTrackToPlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AddTrackToPlaylist400JSONResponse struct{ BadRequestJSONResponse }

func (response AddTrackToPlaylist400JSONResponse) VisitAddTrackToPlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AddTrackToPlaylist401JSONResponse struct{ UnauthorizedJSONResponse }

func (response AddTrackToPlaylist401JSONResponse) VisitAddTrackToPlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AddTrackToPlaylist404JSONResponse struct{ NotFoundJSONResponse }

func (response AddTrackToPlaylist404JSONResponse) VisitAddTrackToPlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AddTrackToPlaylist500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response AddTrackToPlaylist500JSONResponse) VisitAddTrackToPlaylistResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAllTracksRequestObject struct {
}

type GetAllTracksResponseObject interface {
	VisitGetAllTracksResponse(w http.ResponseWriter) error
}

type GetAllTracks200JSONResponse TrackListResponse

func (response GetAllTracks200JSONResponse) VisitGetAllTracksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAllTracks500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetAllTracks500JSONResponse) VisitGetAllTracksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTrackRequestObject struct {
	Body *CreateTrackJSONRequestBody
}

type CreateTrackResponseObject interface {
	VisitCreateTrackResponse(w http.ResponseWriter) error
}

type CreateTrack201JSONResponse TrackResponse

func (response CreateTrack201JSONResponse) VisitCreateTrackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTrack400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateTrack400JSONResponse) VisitCreateTrackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTrack401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateTrack401JSONResponse) VisitCreateTrackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTrack409JSONResponse struct{ ConflictJSONResponse }

func (response CreateTrack409JSONResponse) VisitCreateTrackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTrack500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateTrack500JSONResponse) VisitCreateTrackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTrackRequestObject struct {
	TrackId TrackId `json:"trackId"`
}

type DeleteTrackResponseObject interface {
	VisitDeleteTrackResponse(w http.ResponseWriter) error
}

type DeleteTrack204Response struct {
}

func (response DeleteTrack204Response) VisitDeleteTrackResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTrack400JSONResponse struct{ BadRequestJSONResponse }

func (response DeleteTrack400JSONResponse) VisitDeleteTrackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTrack401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteTrack401JSONResponse) VisitDeleteTrackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTrack404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteTrack404JSONResponse) VisitDeleteTrackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTrack500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteTrack500JSONResponse) VisitDeleteTrackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetTrackByIDRequestObject struct {
	TrackId TrackId `json:"trackId"`
}

type GetTrackByIDResponseObject interface {
	VisitGetTrackByIDResponse(w http.ResponseWriter) error
}

type GetTrackByID200JSONResponse TrackResponse

func (response GetTrackByID200JSONResponse) VisitGetTrackByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTrackByID400JSONResponse struct{ BadRequestJSONResponse }

func (response GetTrackByID400JSONResponse) VisitGetTrackByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetTrackByID404JSONResponse struct{ NotFoundJSONResponse }

func (response GetTrackByID404JSONResponse) VisitGetTrackByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetTrackByID500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetTrackByID500JSONResponse) VisitGetTrackByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTrackRequestObject struct {
	TrackId TrackId `json:"trackId"`
	Body    *UpdateTrackJSONRequestBody
}

type UpdateTrackResponseObject interface {
	VisitUpdateTrackResponse(w http.ResponseWriter) error
}

type UpdateTrack200JSONResponse TrackResponse

func (response UpdateTrack200JSONResponse) VisitUpdateTrackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTrack400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateTrack400JSONResponse) VisitUpdateTrackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTrack401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateTrack401JSONResponse) VisitUpdateTrackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTrack404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateTrack404JSONResponse) VisitUpdateTrackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTrack500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateTrack500JSONResponse) VisitUpdateTrackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login Login user
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout Logout user
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Refresh Refresh access token
	// (POST /auth/refresh)
	Refresh(ctx context.Context, request RefreshRequestObject) (RefreshResponseObject, error)
	// Register Start user registration
	// (POST /auth/register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
	// ResendRegistrationVerification Resend registration verification code
	// (POST /auth/register/resend)
	ResendRegistrationVerification(ctx context.Context, request ResendRegistrationVerificationRequestObject) (ResendRegistrationVerificationResponseObject, error)
	// VerifyRegistration Verify user email during registration
	// (POST /auth/register/verify)
	VerifyRegistration(ctx context.Context, request VerifyRegistrationRequestObject) (VerifyRegistrationResponseObject, error)
	// CreatePlaylist Create playlist
	// (POST /playlists)
	CreatePlaylist(ctx context.Context, request CreatePlaylistRequestObject) (CreatePlaylistResponseObject, error)
	// DeletePlaylist Delete playlist
	// (DELETE /playlists/{playlistId})
	DeletePlaylist(ctx context.Context, request DeletePlaylistRequestObject) (DeletePlaylistResponseObject, error)
	// GetPlaylistByID Get playlist by ID
	// (GET /playlists/{playlistId})
	GetPlaylistByID(ctx context.Context, request GetPlaylistByIDRequestObject) (GetPlaylistByIDResponseObject, error)
	// UpdatePlaylist Update playlist
	// (PUT /playlists/{playlistId})
	UpdatePlaylist(ctx context.Context, request UpdatePlaylistRequestObject) (UpdatePlaylistResponseObject, error)
	// RemoveTrackFromPlaylist Remove track from playlist
	// (DELETE /playlists/{playlistId}/tracks/{trackId})
	RemoveTrackFromPlaylist(ctx context.Context, request RemoveTrackFromPlaylistRequestObject) (RemoveTrackFromPlaylistResponseObject, error)
	// AddTrackToPlaylist Add track to playlist
	// (POST /playlists/{playlistId}/tracks/{trackId})
	AddTrackToPlaylist(ctx context.Context, request AddTrackToPlaylistRequestObject) (AddTrackToPlaylistResponseObject, error)
	// GetAllTracks Get all tracks
	// (GET /tracks)
	GetAllTracks(ctx context.Context, request GetAllTracksRequestObject) (GetAllTracksResponseObject, error)
	// CreateTrack Create track
	// (POST /tracks)
	CreateTrack(ctx context.Context, request CreateTrackRequestObject) (CreateTrackResponseObject, error)
	// DeleteTrack Delete track
	// (DELETE /tracks/{trackId})
	DeleteTrack(ctx context.Context, request DeleteTrackRequestObject) (DeleteTrackResponseObject, error)
	// GetTrackByID Get track by ID
	// (GET /tracks/{trackId})
	GetTrackByID(ctx context.Context, request GetTrackByIDRequestObject) (GetTrackByIDResponseObject, error)
	// UpdateTrack Update track
	// (PUT /tracks/{trackId})
	UpdateTrack(ctx context.Context, request UpdateTrackRequestObject) (UpdateTrackResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(ctx *gin.Context) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx *gin.Context) {
	var request LogoutRequestObject

	var body LogoutJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Refresh operation middleware
func (sh *strictHandler) Refresh(ctx *gin.Context) {
	var request RefreshRequestObject

	var body RefreshJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Refresh(ctx, request.(RefreshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Refresh")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(RefreshResponseObject); ok {
		if err := validResponse.VisitRefreshResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(ctx *gin.Context) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResendRegistrationVerification operation middleware
func (sh *strictHandler) ResendRegistrationVerification(ctx *gin.Context) {
	var request ResendRegistrationVerificationRequestObject

	var body ResendRegistrationVerificationJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ResendRegistrationVerification(ctx, request.(ResendRegistrationVerificationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResendRegistrationVerification")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ResendRegistrationVerificationResponseObject); ok {
		if err := validResponse.VisitResendRegistrationVerificationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VerifyRegistration operation middleware
func (sh *strictHandler) VerifyRegistration(ctx *gin.Context) {
	var request VerifyRegistrationRequestObject

	var body VerifyRegistrationJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.VerifyRegistration(ctx, request.(VerifyRegistrationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VerifyRegistration")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(VerifyRegistrationResponseObject); ok {
		if err := validResponse.VisitVerifyRegistrationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePlaylist operation middleware
func (sh *strictHandler) CreatePlaylist(ctx *gin.Context) {
	var request CreatePlaylistRequestObject

	var body CreatePlaylistJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePlaylist(ctx, request.(CreatePlaylistRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePlaylist")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreatePlaylistResponseObject); ok {
		if err := validResponse.VisitCreatePlaylistResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeletePlaylist operation middleware
func (sh *strictHandler) DeletePlaylist(ctx *gin.Context, playlistId PlaylistId) {
	var request DeletePlaylistRequestObject

	request.PlaylistId = playlistId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeletePlaylist(ctx, request.(DeletePlaylistRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeletePlaylist")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DeletePlaylistResponseObject); ok {
		if err := validResponse.VisitDeletePlaylistResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPlaylistByID operation middleware
func (sh *strictHandler) GetPlaylistByID(ctx *gin.Context, playlistId PlaylistId) {
	var request GetPlaylistByIDRequestObject

	request.PlaylistId = playlistId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPlaylistByID(ctx, request.(GetPlaylistByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPlaylistByID")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetPlaylistByIDResponseObject); ok {
		if err := validResponse.VisitGetPlaylistByIDResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdatePlaylist operation middleware
func (sh *strictHandler) UpdatePlaylist(ctx *gin.Context, playlistId PlaylistId) {
	var request UpdatePlaylistRequestObject

	request.PlaylistId = playlistId

	var body UpdatePlaylistJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdatePlaylist(ctx, request.(UpdatePlaylistRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdatePlaylist")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdatePlaylistResponseObject); ok {
		if err := validResponse.VisitUpdatePlaylistResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RemoveTrackFromPlaylist operation middleware
func (sh *strictHandler) RemoveTrackFromPlaylist(ctx *gin.Context, playlistId PlaylistId, trackId TrackId) {
	var request RemoveTrackFromPlaylistRequestObject

	request.PlaylistId = playlistId
	request.TrackId = trackId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RemoveTrackFromPlaylist(ctx, request.(RemoveTrackFromPlaylistRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RemoveTrackFromPlaylist")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(RemoveTrackFromPlaylistResponseObject); ok {
		if err := validResponse.VisitRemoveTrackFromPlaylistResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddTrackToPlaylist operation middleware
func (sh *strictHandler) AddTrackToPlaylist(ctx *gin.Context, playlistId PlaylistId, trackId TrackId) {
	var request AddTrackToPlaylistRequestObject

	request.PlaylistId = playlistId
	request.TrackId = trackId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AddTrackToPlaylist(ctx, request.(AddTrackToPlaylistRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddTrackToPlaylist")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(AddTrackToPlaylistResponseObject); ok {
		if err := validResponse.VisitAddTrackToPlaylistResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAllTracks operation middleware
func (sh *strictHandler) GetAllTracks(ctx *gin.Context) {
	var request GetAllTracksRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllTracks(ctx, request.(GetAllTracksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllTracks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetAllTracksResponseObject); ok {
		if err := validResponse.VisitGetAllTracksResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTrack operation middleware
func (sh *strictHandler) CreateTrack(ctx *gin.Context) {
	var request CreateTrackRequestObject

	var body CreateTrackJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTrack(ctx, request.(CreateTrackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTrack")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateTrackResponseObject); ok {
		if err := validResponse.VisitCreateTrackResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteTrack operation middleware
func (sh *strictHandler) DeleteTrack(ctx *gin.Context, trackId TrackId) {
	var request DeleteTrackRequestObject

	request.TrackId = trackId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTrack(ctx, request.(DeleteTrackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTrack")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DeleteTrackResponseObject); ok {
		if err := validResponse.VisitDeleteTrackResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTrackByID operation middleware
func (sh *strictHandler) GetTrackByID(ctx *gin.Context, trackId TrackId) {
	var request GetTrackByIDRequestObject

	request.TrackId = trackId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTrackByID(ctx, request.(GetTrackByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTrackByID")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetTrackByIDResponseObject); ok {
		if err := validResponse.VisitGetTrackByIDResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTrack operation middleware
func (sh *strictHandler) UpdateTrack(ctx *gin.Context, trackId TrackId) {
	var request UpdateTrackRequestObject

	request.TrackId = trackId

	var body UpdateTrackJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTrack(ctx, request.(UpdateTrackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTrack")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdateTrackResponseObject); ok {
		if err := validResponse.VisitUpdateTrackResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Fzdc9u4Ef9XMOjN9IWxZDmXJnpjHOWqVv4oTfsu9bgamIQkXEiCB4BOVI/+9w4AfkEEJVqxdEn9ZoLE",
	"YrH7w35h5UcY0DilCU4Eh8NHmCKGYiwwU0+XEVpGhItxKJ9CzANGUkFoAoflO0BCnAgyI5hBBxL5KkVi",
	"AR2YoBjLp4qIAxn+IyMMh3AoWIYdyIMFjpGkHpNkgpO5WMDhsQPFMpVzuWAkmcPVyoE+Q8FnGyPqxVYu",
	"RD59dxZWcipPacKxEs57FHr4jwxzIZ8CmgicqD9RmkYkQJK93u9c8vhYW+QnhmdwCP/SqwTf0295b8QY",
	"ZV6+iF7S3Os4eUARCQHLF1458JQms4gEB2TCw5xmLMAgKJZeOXCcCMwSFF1h9oCZonFIsejFAVerA6yW",
	"XznwnIqPNEvCP0E4CRVgptaW4KX0DCXLHC/8cOz4lIIYJcsCMRw6cIFRmB9wDwu2fOXOBGbNg3WexfeY",
	"AToDHAc0CTlA8kPwZUGCBRALDIKI4ESAGEn6gi3VYL7SEawfrRllMRJwCEkiTgbQkWeNxFkMh/3ypJFE",
	"4DlmchsrB14nKBMLysh/8QHV52ZiIQ2Jpg5KWyG/zInINeRnJRlpNhlNMRNEWwYUBJjzqaCfseJtzZI4",
	"EH9NCcN8SpLNsjluykYaoRnDfLGBvHoz1cOPECeS1C18jxHDDN7ZjGtlE29N7teXM3g3Vqro0vvfsTYK",
	"pwwjgQtPUbOWKAyJFDCKLmuSm6GIY2dNmNp+P0L8FcVpJOmfLcGvlH2mmZCyQl8Lmz3o953NNtyBD4ST",
	"exIRsdwGlYLrm2rGuqQUa+37Vo5pt02j6D6LXSauvYmBkIwRaNmV+twnIsJWPCAmiGahJq2TDtKa44Qp",
	"kkTgmNuxpgcQY2gpn0loKkv53Vf9/jHculrK8APBXzruWRTbfeKeMhZ1Ib/EiOXU9VkcHOfE86P5rm+z",
	"XCZAiIw3NKOlFjQHhs4cQ9+GIAod5AzZwGbatIYxwoUrNocDGhrWYXx+407GH6be6F/XoysfOuXI5cT9",
	"NBlbh6bjD7bRc/dsBB1YPV/4048X1+fyY99zT/9pjJSfuRNv5H74NB39Nr7yrxRhf+Sdu5PpyPMuvNpK",
	"isj6s8mMHvLH/mTUGHU939yPHtbyNsc+jVyv5LrB4PXVyGuO3oy88cfxqeuPL86nObn14dFvl2Nv1Bj2",
	"Ly6mZ+75p6nr+6OzyyY5z/VH08n4bOyrydfn7rX/9wtv/O9RffOn3ujD6Nwfu5MrCZnqNFpV0sB+jDlH",
	"8zWrW4TxtcBmmydRGKvINcG79r2Gqg3jEzonyW6mFMeImCdejxiu42RgGo6fbeYJcf6FstCgVQ4a5I4H",
	"bw1yb7dJqmCpJNciBJrt6EUbQcO2dKvOnTnZxtqZVnG7FQqRQM1RK9CUxwAoDHEIBAUF7rairTPMFC+2",
	"XRQuv8ko6ZwAV/t48yZ4e/83PLjv43fBG/Q2eIcG4fHgxHbiiiCnZQX12nmmEEjJl2/Po7nM7wQiCQ4B",
	"SVRoX9NFycut4eKLvwdSwN2jhmcNy5TXzUWWb3aTtreDtgs/T0fZjbHnwg+njDwgIVlPs/uIBJZ43YGe",
	"PpDfpSnw8JxwgdlLt9aVHFojs2/JAh8wI7M8TZ0Sc5tZRrY753UCRmbXviGmJtzUJu9pg6qgMEVFaeJJ",
	"BYR9i8fkzi4sjpOwXWS7nI1n35ONceUFLCUNMyGtPNFCiJQPe7185CigcU99fPR7OofOE1PXiq4rx60T",
	"ymS29nGRWu2a39a8mUeDz9CBbqRKioI84Ke5sk0J8JaUd7NU82+P4vSkg1xFU6RXNJmDIuPcLWvezCGn",
	"ybwje0V6XRIc9Ac/Oz9Atq3Ox6RT2FBiZlP8oM9bA0ddg4m8xvQtEUzOQdcVr9NwDzU9TTX83gt7ms0X",
	"Wdj7/6vO7dtUXPON0V9rpNvY7S6+XocsiqKNNxWNLOvxyW54LsqIKRLSX8Ih/M9t/9W7u8c3q59sW9lD",
	"XKZYsCb9HAcZI2J5JU++5vdeXYK4mcRf8fSxYOAfv/rFpZWkpN9WHEmXp++MSDKjzQTaG135wL0cgxll",
	"4OrVzfhy5IE44yRQ95IkwKV/GsLivXs5hkosXBM5Puof9aWkaIoTlBI4hCdH/aMTlW6IhdpED2Vi0Yvo",
	"XAfWKdVqa73JwhwgoAWHQ5BxzABKQhCoWwoOUAJQ7eMQcMwlN0dQcaHhMQ7hUJfh8it0zMV7Gi6f7WrO",
	"KPGtTLULluH16/dBv/9saxvXedtvBXmmrshmWSQV9VozYqNfMtyrNQuoKcfbpxgXoCsH/txlHds1fP0o",
	"wOHtnQN5FseILQuNKkhIbKI5l2dMHY87Oa1EmvTJrVDz8AP9jLkqEfFMagGHIK8UAFUpsEJJ+/k9YalW",
	"Ke0EptfNbU3ofI5DINncTc370hjNxDaV5dLfoDMq1OHXN/Y1VSnTwLDIWCLNRoK/AH0jnL9OEWFNdeYV",
	"qT3pc63e9Z1ZB1/KhRdS1If1hzYKubgNvW/Emq50tYPttPA0IMVJSJI5YLXIQyGOY9VgAur+HUjXDgRV",
	"IJWA/ysHKqSx4S/nYV8ANIuanRA42MPymxqPahLlAjHpyaVkmxLlkqFdQfpu+5TTWl/Y60GHCevtUfsC",
	"9pUUiw6A6gDsgG25KNZ9ZHaIX+X4lfayKXEZEdrBb4PyptLh3gDepV75p8B+Q8XZcgxunhftr7dPKXsM",
	"vze0a52aprYBzS7YV5OW7djXMs+DCWWgAQpDJn1HxiXgVa9goQsQZmz7KWgmqHtCfnsm3Antx8/GiFEu",
	"sCD7ujJbmOW2XQu7SO0OhvIf2glohWsvoOVnAaT9WBT337x+Fkzcmi2Pe8Ksva/ywHht3J9bMFt2MOha",
	"w0FD4yej9NvQVuJLK8foW8mRdFnCZw1OvcfqRxIrbV8jLHATXR/UuIGubVlsqQJN88AqeKJleSYVaDFt",
	"U4ED59hazdC5b9nwRr8kOAT3urvdrJRJI9L0Xb9gUazzfql6//aWmz7lEB7KPezFav+CRaWR+yVQYrVr",
	"tf4bpls7H9UnvdpvnFZ3Dkwzi1E377z2ZNTtF2sHrnU8yahn+tLuJVgUrZzdjXpPN6L1HvPfoW208h6O",
	"6YO+ZfzIaPwkc6+7+JiiEIIZo3HF9AvQkxYd0D2k5u6f31w4W78ufrSoLIs1XnTDUH3k03Y1P9/xXu/T",
	"tVUzW9pvXwB43DDMkbPWd9xy1KtO2jyQaIQBbhT5+qM9KrXZktKmVr5X94yiCIhit4XM8nXVQduQMOkm",
	"lH1mS0bTxoFTJbNLp/XQvbwkSeRqb6ClOl7dXKaO+CsUdXOTLy8lahW402rD1Cf7zmO6nZAfPoPR3mU9",
	"fanbyCcFI0Z40Z647NO4WjriDpyydDSuLy9ZaTeuJkrNrqjbO4km/Y8UNAjXemEux+DhOO+WG8IeSknv",
	"4VhBMF+otQJVYpNX/5ejiqlkOG1TnG1WGc08bu7Usc1V21zdrf4XAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
